### ISSUE TITLE
Dependency conflict while installing

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan-webapp#1]
Hey @jwparktom , I tried to get this run locally, but ran into errors when doing `npm install`, looks like there are some dependency package conflicts, but I'm new to this so not sure how best to fix it. I'm attaching the log and shell output here so you can see my npm version as well. Hopefully it's just a matter of relaxing/narrowing some package versions, thanks!

[eresolve-report.txt](https://github.com/QSD-Group/QSDsan-Website/files/7581690/eresolve-report.txt)

[2021-11-22T13_50_00_748Z-debug.log](https://github.com/QSD-Group/QSDsan-Website/files/7581698/2021-11-22T13_50_00_748Z-debug.log)

<img width="886" alt="Screen Shot 2021-11-22 at 7 59 32 AM" src="https://user-images.githubusercontent.com/49011373/142874436-0eaa0c6b-72ac-4d08-99d6-e449d0d72fb9.png">

**Comment by jdubpark** [comment]
Yes, I also faced that error. Since we plan to use React 17, you can solve it with the `--force` flag. So run
```bash
npm install --force
```

I will update the README.md to reflect the command.

**Comment by yalinli2** [comment]
Thanks @jwparktom , I added the `--force` flag, however now it's prompting something else:

<img width="1159" alt="Screen Shot 2021-11-22 at 9 08 55 PM" src="https://user-images.githubusercontent.com/49011373/142965972-90162139-df08-4100-b5ca-e17faceff9db.png">

Have you run into these? If not I'll just follow the steps to see if I can get it fixed, thanks!

PS, I updated the README with some links to get `npm`, feel free to edit as you see fit!

**Comment by jdubpark** [comment]
That's weird 🤔. I've just removed the `lottie-react` package since it's known to cause the dependency error between React versions. So running these commands (line by line) should make the app work now!
```bash
git pull
rm package-lock.json
npm install
npm start
```

**Comment by yalinli2** [comment]
Unfortunately	that didn't work, so I followed the instructions in 

> <img alt="Screen Shot 2021-11-22 at 9 08 55 PM" width="1159" src="https://user-images.githubusercontent.com/49011373/142965972-90162139-df08-4100-b5ca-e17faceff9db.png">

Steps 1-4 didn't work and I didn't want to mess with yarn, but following step 7 shows that two of the libraries have different requirement toward `babel-loader` and I think that's the culprit:

<img width="679" alt="Screen Shot 2021-11-23 at 12 17 48 PM" src="https://user-images.githubusercontent.com/49011373/143081573-52967ade-e714-4d71-9ba7-569c8700a2ca.png">

I'm not sure if that's something you can fix in `package.json`

Since it looks like you could ignore this error, so I added the `.env` file to skip the check, and it worked 

BTW, it took a solid 5-10 sec to load the page, is it normal? When using Jekyll, it's like instant, but probably because it's static.

Thanks!!!

**Comment by jdubpark** [comment]
I will try to find what's wrong with the dependencies, but I think you are right. The upside of node/npm is the richness of dependencies, and the downside is the hassle of linking the old and new ones together.

Yes, the first load of `npm start` always takes some time since it's building the whole source code. Once that's done though, the hot reloading should happen almost immediately. Jekyll and other static frameworks (like Hugo or Gatsby) are built to be fast and simple :)

**Comment by yalinli2** [comment]
ah I see, thanks Jongwon! I'll close this now, but if you fix the dependencies in the future, it'll be great to tag this issue, thanks!
